# Generated by Django 5.1.4 on 2024-12-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_remove_currencystats_avg_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_amount',
            name='value_in_som',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
