# Generated by Django 5.1.4 on 2024-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currency_amount_value_in_som'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_amount',
            name='value_in_som',
        ),
        migrations.AddField(
            model_name='currency_amount',
            name='is_som',
            field=models.BooleanField(default=False),
        ),
    ]
