# Generated by Django 5.1.4 on 2024-12-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_remove_currency_amount_value_in_som_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_amount',
            name='is_som',
        ),
    ]
