# Generated by Django 5.1.4 on 2024-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_remove_currency_amount_is_som'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystats',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
