# Generated by Django 5.1.4 on 2024-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_currencystats_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
